### 3.3.1. Задача 1: "Трансформация матриц в numpy"

Создайте две матрицы по формулам,
воспользовавшись типом «numpy.array(some_list)» и
командой «numpy.fromfunction(function)», для них вычислите:

- Вычислите Aᵀ и Bᵀ;
- Вычислите A + B;
- Вычислите A - B;
- Вычислите A * B и B * A;
- Вычислите A / B и B / A;
- Вычислите A // B и B // A;
- Вычислите A⁻¹ и B⁻¹;
- Вычислите A * B⁻¹ и B * A⁻¹;
- Вычислите значение 2Aᵀ - E, где E — единичная матрица, размера MxN, при том,
что изначально матрица A имеет размер NxM.
- Вычислите значение многочлена 𝑓(𝑥) = 𝑥³ − 7𝑥² + 13𝑥 − 5, если 𝑥 — это матрицы A и B;
- Вычислите значения функции 1 и функции 2 из Таблицы 2 для матриц A и B;
- Вычислите значения функции 3 из Таблицы 2, приняв что переменная
«у» — это матрица A, а переменная «𝑥𝑥» — это матрица B;

При этом учтите, что здесь знак «*» обозначает матричное умножение,
а не поэлементное.

In [1]:
import numpy as np
import math

# Установка параметров для красивого вывода
np.set_printoptions(precision=3, suppress=True)

<h3 style="text-align: center">Создание матриц A и B по формулам варианта 1</h3>

In [2]:
# Матрица A[i,j] = (i! - j!) / i!
def A_func(i, j):
    i = i + 1  # Индексация с 1
    j = j + 1
    i_fact = np.vectorize(math.factorial)(i)
    j_fact = np.vectorize(math.factorial)(j)
    return (i_fact - j_fact) / i_fact

# Матрица B[i,j] = (i - j) / (i + j)
def B_func(i, j):
    i = i + 1
    j = j + 1
    with np.errstate(divide='ignore', invalid='ignore'):
        result = (i - j) / (i + j)
        result[(i + j) == 0] = 0
    return result

# Размеры по варианту 1:
# A — 10x20, B — 20x10
A = np.fromfunction(A_func, (10, 20), dtype=int)
B = np.fromfunction(B_func, (20, 10), dtype=int)

<h3 style="text-align: center">1. Вычислите: Aᵀ и Bᵀ</h3>

In [3]:
print("1. Транспонированные матрицы A.T и B.T:")
print("A.T:\n", A.T)
print("\nB.T:\n", B.T)

1. Транспонированные матрицы A.T и B.T:
A.T:
 [[ 0.000e+00  5.000e-01  8.333e-01  9.583e-01  9.917e-01  9.986e-01
   9.998e-01  1.000e+00  1.000e+00  1.000e+00]
 [-1.000e+00  0.000e+00  6.667e-01  9.167e-01  9.833e-01  9.972e-01
   9.996e-01  1.000e+00  1.000e+00  1.000e+00]
 [-5.000e+00 -2.000e+00  0.000e+00  7.500e-01  9.500e-01  9.917e-01
   9.988e-01  9.999e-01  1.000e+00  1.000e+00]
 [-2.300e+01 -1.100e+01 -3.000e+00  0.000e+00  8.000e-01  9.667e-01
   9.952e-01  9.994e-01  9.999e-01  1.000e+00]
 [-1.190e+02 -5.900e+01 -1.900e+01 -4.000e+00  0.000e+00  8.333e-01
   9.762e-01  9.970e-01  9.997e-01  1.000e+00]
 [-7.190e+02 -3.590e+02 -1.190e+02 -2.900e+01 -5.000e+00  0.000e+00
   8.571e-01  9.821e-01  9.980e-01  9.998e-01]
 [-5.039e+03 -2.519e+03 -8.390e+02 -2.090e+02 -4.100e+01 -6.000e+00
   0.000e+00  8.750e-01  9.861e-01  9.986e-01]
 [-4.032e+04 -2.016e+04 -6.719e+03 -1.679e+03 -3.350e+02 -5.500e+01
  -7.000e+00  0.000e+00  8.889e-01  9.889e-01]
 [-3.629e+05 -1.814e+05 -6.048e+04

<h3 style="text-align: center">2. Вычислите: A + B</h3>

In [4]:
print("\n2. A + B (приводим к одинаковому размеру 10x10):")
A_small = A[:, :10]
B_small = B[:10, :]
print(A_small + B_small)


2. A + B (приводим к одинаковому размеру 10x10):
[[       0.          -1.333       -5.5        -23.6       -119.667
      -719.714    -5039.75    -40319.778  -362879.8   -3628799.818]
 [       0.833        0.          -2.2        -11.333      -59.429
      -359.5      -2519.556   -20159.6    -181439.636 -1814399.667]
 [       1.333        0.867        0.          -3.143      -19.25
      -119.333     -839.4      -6719.455   -60479.5    -604799.538]
 [       1.558        1.25         0.893        0.          -4.111
       -29.2       -209.273    -1679.333   -15119.385  -151199.429]
 [       1.658        1.412        1.2          0.911        0.
        -5.091      -41.167     -335.231    -3023.286   -30239.333]
 [       1.713        1.497        1.325        1.167        0.924
         0.          -6.077      -55.143     -503.2      -5039.25 ]
 [       1.75         1.555        1.399        1.268        1.143
         0.934        0.          -7.067      -71.125     -719.176]
 [       

<h3 style="text-align: center">3. Вычислите: A - B</h3>

In [5]:
print("\n3. A - B:")
print(A_small - B_small)


3. A - B:
[[       0.          -0.667       -4.5        -22.4       -118.333
      -718.286    -5038.25    -40318.222  -362878.2   -3628798.182]
 [       0.167        0.          -1.8        -10.667      -58.571
      -358.5      -2518.444   -20158.4    -181438.364 -1814398.333]
 [       0.333        0.467        0.          -2.857      -18.75
      -118.667     -838.6      -6718.545   -60478.5    -604798.462]
 [       0.358        0.583        0.607        0.          -3.889
       -28.8       -208.727    -1678.667   -15118.615  -151198.571]
 [       0.325        0.555        0.7          0.689        0.
        -4.909      -40.833     -334.769    -3022.714   -30238.667]
 [       0.284        0.497        0.658        0.767        0.742
         0.          -5.923      -54.857     -502.8      -5038.75 ]
 [       0.25         0.444        0.599        0.723        0.81
         0.78         0.          -6.933      -70.875     -718.824]
 [       0.222        0.4          0.545        0

<h3 style="text-align: center">4. Вычислите: A * B и B * A (поэлементно)</h3>

In [6]:
print("\n4. A * B (поэлементно):")
print(A_small * B_small)
print("\n4. B * A (поэлементно):")
print(B_small * A_small)
print("\n4a. A @ B (матричное умножение):")
print(A_small @ B_small)
print("\n4a. B @ A (матричное умножение):")
print(B_small @ A_small)


4. A * B (поэлементно):
[[      0.          0.333       2.5        13.8        79.333     513.571
     3779.25    31359.222  290303.2   2969017.364]
 [      0.167       0.          0.4         3.667      25.286     179.5
     1399.444   12095.4    115461.182 1209599.333]
 [      0.417       0.133       0.          0.429       4.75       39.667
      335.6      3054.091   30239.5    325661.   ]
 [      0.575       0.306       0.107       0.          0.444       5.8
       57.        559.667    5815.      64799.571]
 [      0.661       0.421       0.237       0.089       0.          0.455
        6.833      77.308     863.714   10079.667]
 [      0.713       0.499       0.331       0.193       0.076       0.
        0.462       7.857     100.6      1259.75 ]
 [      0.75        0.555       0.4         0.271       0.163       0.066
        0.          0.467       8.875     126.882]
 [      0.778       0.6         0.454       0.333       0.23        0.14
        0.058       0.          0.

<h3 style="text-align: center">5. Вычислите: A / B и B / A (поэлементно)</h3>

In [7]:
print("\n5. A / B:")
print(np.divide(A_small, B_small, where=B_small!=0))
print("\n5. B / A:")
print(np.divide(B_small, A_small, where=A_small!=0))


5. A / B:
[[      -5.679        3.          10.          38.333      178.5
      1006.6       6718.667    51838.714   453598.75   4435198.778]
 [       1.5         -4.151       10.          33.         137.667
       718.        4534.2      33598.333   285118.429  2721598.5  ]
 [       1.667        3.333       -5.468       21.          76.
       357.        2097.5      14781.8     120958.     1123198.143]
 [       1.597        2.75         5.25       -19.595       36.
       145.         766.333     5037.       39309.4     352797.667]
 [       1.488        2.294        3.8          7.2       -110.901
        55.         246.        1451.667    10580.5      90717.   ]
 [       1.398        1.994        2.975        4.833        9.167
      -739.648       78.         385.        2515.       20156.   ]
 [       1.333        1.799        2.497        3.649        5.857
        11.143    -5578.947      105.         568.        4074.333]
 [       1.286        1.667        2.2          2.99

<h3 style="text-align: center">6. Вычислите: A // B и B // A (целочисленное деление)</h3>

In [9]:
print("\n6. A // B (целочисленно):")
with np.errstate(divide='ignore', invalid='ignore'):
    result1 = np.floor_divide(A_small, B_small, where=B_small!=0)
    result1[B_small == 0] = 0
print(result1)


6. A // B (целочисленно):
[[      0.       3.      10.      38.     178.    1006.    6718.   51838.
   453598. 4435198.]
 [      1.       0.       9.      33.     137.     718.    4534.   33598.
   285118. 2721598.]
 [      1.       3.       0.      21.      76.     357.    2097.   14781.
   120958. 1123198.]
 [      1.       2.       5.       0.      36.     144.     766.    5037.
    39309.  352797.]
 [      1.       2.       3.       7.       0.      54.     246.    1451.
    10580.   90717.]
 [      1.       1.       2.       4.       9.       0.      77.     385.
     2514.   20156.]
 [      1.       1.       2.       3.       5.      11.       0.     105.
      568.    4074.]
 [      1.       1.       2.       2.       4.       6.      13.       0.
      136.     801.]
 [      1.       1.       1.       2.       3.       4.       7.      15.
        0.     171.]
 [      1.       1.       1.       2.       2.       3.       5.       8.
       17.       0.]]


In [10]:
print("\n6. B // A (целочисленно):")
with np.errstate(divide='ignore', invalid='ignore'):
    result2 = np.floor_divide(B_small, A_small, where=A_small!=0)
    result2[A_small == 0] = 0
print(result2)


6. B // A (целочисленно):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<h3 style="text-align: center">7. Вычислите A⁻¹ и B⁻¹</h3>

In [11]:
print("\n7. Обратные матрицы A⁻¹ и B⁻¹ (используем квадратные версии):")
A_square = A[:, :10]
B_square = B[:10, :]
try:
    A_inv = np.linalg.inv(A_square)
    B_inv = np.linalg.inv(B_square)
    print("A⁻¹:\n", A_inv)
    print("\nB⁻¹:\n", B_inv)
except np.linalg.LinAlgError:
    print("Матрицы A или B не обратимы")


7. Обратные матрицы A⁻¹ и B⁻¹ (используем квадратные версии):
A⁻¹:
 [[-3.255e+13  4.027e+13  3.379e+13 -4.681e+13  4.745e+14  4.592e+15
  -8.529e+15  3.523e+15  3.143e+15 -3.198e+15]
 [-8.037e+13  1.221e+14  2.411e+13 -2.476e+13  7.125e+14  8.178e+15
  -2.772e+15 -1.712e+16  8.077e+15  2.878e+15]
 [ 7.266e+13 -1.307e+14 -2.728e+13  4.943e+13 -2.955e+14 -3.695e+15
   1.278e+16  1.006e+16 -9.646e+15 -9.159e+15]
 [-5.522e+13  6.944e+13  2.254e+13 -2.484e+13  7.908e+14  8.392e+15
  -4.138e+14 -1.532e+16 -1.967e+15  8.508e+15]
 [ 7.037e+13 -1.407e+14 -0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00
  -0.000e+00 -0.000e+00 -0.000e+00  7.037e+13]
 [ 2.652e+13  3.606e+13 -6.614e+13  4.756e+13 -1.640e+15 -1.589e+16
  -1.037e+15  1.723e+16  3.748e+14  9.181e+14]
 [-8.939e+11  4.506e+12  9.646e+12 -4.296e+12 -4.455e+13 -1.768e+15
  -2.854e+13  1.829e+15  2.238e+13 -1.861e+13]
 [-4.791e+11 -8.910e+11  3.441e+12  3.584e+12 -1.317e+12  1.555e+14
   4.121e+12 -1.623e+14 -3.997e+12  2.338e+12]
 [-2.831e+1

<h3 style="text-align: center">8. Вычислите: A * B⁻¹ и B * A⁻¹</h3>

In [12]:
print("\n8. A * B⁻¹ и B * A⁻¹:")
try:
    print("A * B⁻¹:\n", A_square @ B_inv)
    print("\nB * A⁻¹:\n", B_square @ A_inv)
except:
    print("Умножение невозможно из-за формы или необратимости")


8. A * B⁻¹ и B * A⁻¹:
A * B⁻¹:
 [[ 9.188e+12 -2.044e+14  1.932e+15 -9.559e+15  2.728e+16 -4.667e+16
   4.762e+16 -2.727e+16  7.360e+15 -4.906e+14]
 [ 4.594e+12 -1.022e+14  9.659e+14 -4.779e+15  1.364e+16 -2.334e+16
   2.381e+16 -1.364e+16  3.680e+15 -2.453e+14]
 [ 1.531e+12 -3.407e+13  3.220e+14 -1.593e+15  4.546e+15 -7.779e+15
   7.937e+15 -4.546e+15  1.227e+15 -8.177e+13]
 [ 3.828e+11 -8.517e+12  8.050e+13 -3.983e+14  1.137e+15 -1.945e+15
   1.984e+15 -1.136e+15  3.067e+14 -2.044e+13]
 [ 7.657e+10 -1.703e+12  1.610e+13 -7.966e+13  2.273e+14 -3.889e+14
   3.969e+14 -2.273e+14  6.133e+13 -4.089e+12]
 [ 1.276e+10 -2.839e+11  2.683e+12 -1.328e+13  3.788e+13 -6.482e+13
   6.614e+13 -3.788e+13  1.022e+13 -6.814e+11]
 [ 1.823e+09 -4.056e+10  3.833e+11 -1.897e+12  5.412e+12 -9.260e+12
   9.449e+12 -5.412e+12  1.460e+12 -9.735e+10]
 [ 2.279e+08 -5.070e+09  4.791e+10 -2.371e+11  6.765e+11 -1.158e+12
   1.181e+12 -6.765e+11  1.825e+11 -1.217e+10]
 [ 2.532e+07 -5.633e+08  5.324e+09 -2.634e+10  

<h3 style="text-align: center">9. Вычислите 2Aᵀ - E, где E — единичная матрица 10x10</h3>

In [13]:
print("\n9. Выражение 2Aᵀ - E:")
E = np.identity(10)
print(2 * A_square.T - E)


9. Выражение 2Aᵀ - E:
[[      -1.           1.           1.667        1.917        1.983
         1.997        2.           2.           2.           2.   ]
 [      -2.          -1.           1.333        1.833        1.967
         1.994        1.999        2.           2.           2.   ]
 [     -10.          -4.          -1.           1.5          1.9
         1.983        1.998        2.           2.           2.   ]
 [     -46.         -22.          -6.          -1.           1.6
         1.933        1.99         1.999        2.           2.   ]
 [    -238.        -118.         -38.          -8.          -1.
         1.667        1.952        1.994        1.999        2.   ]
 [   -1438.        -718.        -238.         -58.         -10.
        -1.           1.714        1.964        1.996        2.   ]
 [  -10078.       -5038.       -1678.        -418.         -82.
       -12.          -1.           1.75         1.972        1.997]
 [  -80638.      -40318.      -13438.       -

<h3 style="text-align: center">10. Вычислите значение многочлена f(x) = x³ - 7x² + 13x - 5 для A и B</h3>

In [14]:
def poly_f(x):
    return x @ x @ x - 7 * x @ x + 13 * x - 5 * np.identity(x.shape[0])

print("\n10. Многочлен f(x) = x³ - 7x² + 13x - 5 от A:")
try:
    print(poly_f(A_square))
except:
    print("Ошибка вычисления многочлена от A")

print("\n10. Многочлен f(x) = x³ - 7x² + 13x - 5 от B:")
try:
    print(poly_f(B_square))
except:
    print("Ошибка вычисления многочлена от B")


10. Многочлен f(x) = x³ - 7x² + 13x - 5 от A:
[[ 2.827e+07  3.520e+07  6.296e+07  1.878e+08  8.539e+08  5.017e+09
   3.499e+10  2.798e+11  2.518e+12  2.518e+13]
 [ 1.066e+07  1.413e+07  2.801e+07  9.045e+07  4.235e+08  2.505e+09
   1.749e+10  1.399e+11  1.259e+12  1.259e+13]
 [-1.071e+06  8.539e+04  4.711e+06  2.553e+07  1.365e+08  8.304e+08
   5.826e+09  4.662e+10  4.196e+11  4.196e+12]
 [-5.471e+06 -5.182e+06 -4.026e+06  1.178e+06  2.893e+07  2.024e+08
   1.451e+09  1.165e+10  1.049e+11  1.049e+12]
 [-6.645e+06 -6.587e+06 -6.356e+06 -5.315e+06  2.368e+05  3.493e+07
   2.848e+08  2.325e+09  2.098e+10  2.098e+11]
 [-6.889e+06 -6.880e+06 -6.841e+06 -6.667e+06 -5.741e+06  4.777e+04
   4.173e+07  3.821e+08  3.494e+09  3.500e+10]
 [-6.931e+06 -6.930e+06 -6.924e+06 -6.899e+06 -6.766e+06 -5.933e+06
   6.608e+04  4.906e+07  4.970e+08  5.032e+09]
 [-6.937e+06 -6.937e+06 -6.936e+06 -6.933e+06 -6.915e+06 -6.805e+06
  -6.010e+06  4.855e+05  5.987e+07  6.611e+08]
 [-6.938e+06 -6.938e+06 -6.938e+0

<h3 style="text-align: center">11. Вычислите значения функции 1 и функции 2 из Таблицы 2 для матриц A и B</h3>

In [15]:
# Функция 1: y(x) = sin(3x)
# Функция 2: y(x) = 2cos(x)

print("\n11. Функция 1 (y = sin(3x)) для матрицы A:")
print(np.sin(3 * A_small))

print("\n11. Функция 2 (y = 2cos(x)) для матрицы B:")
print(2 * np.cos(B_small))



11. Функция 1 (y = sin(3x)) для матрицы A:
[[ 0.    -0.141 -0.65   0.115  0.909 -0.956  0.337  0.565  0.25   0.613]
 [ 0.997  0.     0.279 -1.    -0.878 -0.536  0.995 -0.974  0.998  0.967]
 [ 0.598  0.909  0.    -0.412 -0.436  0.909  0.552 -0.515  0.564 -1.   ]
 [ 0.263  0.382  0.778  0.     0.537  0.822  0.968  0.856  0.967 -0.96 ]
 [ 0.166  0.19   0.287  0.675  0.    -0.65   0.46   0.305 -0.702 -0.362]
 [ 0.145  0.149  0.166  0.239  0.598  0.     0.751 -0.998 -0.86   0.337]
 [ 0.142  0.142  0.145  0.155  0.211  0.54   0.    -0.837  0.588 -0.956]
 [ 0.141  0.141  0.142  0.143  0.15   0.194  0.494  0.     0.906 -0.035]
 [ 0.141  0.141  0.141  0.141  0.142  0.147  0.182  0.457  0.    -0.956]
 [ 0.141  0.141  0.141  0.141  0.141  0.142  0.145  0.174  0.427  0.   ]]

11. Функция 2 (y = 2cos(x)) для матрицы B:
[[2.    1.89  1.755 1.651 1.572 1.511 1.463 1.425 1.393 1.367]
 [1.89  2.    1.96  1.89  1.819 1.755 1.699 1.651 1.609 1.572]
 [1.755 1.96  2.    1.98  1.938 1.89  1.842 1.797 1.755

<h3 style="text-align: center">Вычислите значения функции 3 из Таблицы 2, приняв: переменная «у» — это матрица A, переменная «x» — это матрица B.Формула: Z(x, y) = (x! - y!) / x!</h3>

In [17]:
print("\n12. Функция 3: Z(x, y) = (x! - y!) / x! где x = B, y = A:")

def factorial_safe(mat):
    """Вычисление факториала с защитой от переполнений"""
    mat_int = np.clip(mat.astype(int), 0, 170)  # факториалы >170 не считаем
    return np.vectorize(math.factorial, otypes=[float])(mat_int)

try:
    # Отображаем значения до округления
    print("A_small (как y):\n", np.round(A_small, 2))
    print("B_small (как x):\n", np.round(B_small, 2))

    # Считаем факториалы
    x_fact = factorial_safe(B_small)
    y_fact = factorial_safe(A_small)

    with np.errstate(divide='ignore', invalid='ignore', over='ignore'):
        Z = (x_fact - y_fact) / x_fact
        Z[np.isnan(Z)] = 0
        Z[np.isinf(Z)] = 0
        Z = np.where(x_fact == 0, 0, Z)  # защита от деления на 0

    print("Z = (x! - y!) / x!:\n", np.round(Z, 3))

except Exception as e:
    print("Ошибка при вычислении функции 3:", e)



12. Функция 3: Z(x, y) = (x! - y!) / x! где x = B, y = A:
A_small (как y):
 [[       0.         -1.         -5.        -23.       -119.       -719.
     -5039.     -40319.    -362879.   -3628799.  ]
 [       0.5         0.         -2.        -11.        -59.       -359.
     -2519.     -20159.    -181439.   -1814399.  ]
 [       0.83        0.67        0.         -3.        -19.       -119.
      -839.      -6719.     -60479.    -604799.  ]
 [       0.96        0.92        0.75        0.         -4.        -29.
      -209.      -1679.     -15119.    -151199.  ]
 [       0.99        0.98        0.95        0.8         0.         -5.
       -41.       -335.      -3023.     -30239.  ]
 [       1.          1.          0.99        0.97        0.83        0.
        -6.        -55.       -503.      -5039.  ]
 [       1.          1.          1.          1.          0.98        0.86
         0.         -7.        -71.       -719.  ]
 [       1.          1.          1.          1.          1. 